### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by mitchstewart08** [andrewhead/Alfred-Habitica#1]
I'd love to use this but there is no readme :(

**Comment by andrewhead** [comment]
Hi Mitch.  Thanks for your note!  Let me see what I can do in the README department this weekend.

**Comment by andrewhead** [comment]
Hi Mitch.  Sorry that this took a couple of months for my cycles to clear up.  In the meantime, I've put together a README and a version of the package in workflow form that you should be able to download and take for a spin.  If you're still looking for something simple and lightweight to try out, go ahead and give it a shot, and I'd love to hear what you think!
