### ISSUE TITLE
Can't do anything beyond config

### ISSUE THREAD

**Issue by Wickemu** [andrewhead/Alfred-Habitica#5]
I can get the configuration (seemingly) working, but any time I attempt to add or address a task, Alfred almost immediately resorts to my fallbacks after the initial keyword. Any suggestions?

**Comment by andrewhead** [comment]
Hi Wickemu.  Thank you for your interest!  Hopefully I have resolved this issue.  Can you try again with the updated link in the README?  The Alfred workflow was behind in its version of the Habitica API, causing it to crash.  It has now been updated.

**Comment by Wickemu** [comment]
That did it! Thank you, very excited to use this!
